In [24]:
## Michael Janke - Assignment 2
## Import Modules
import numpy as np
import pandas as pd

In [25]:
## Read train term matrix (5500 terms, 800 documents)
## Term frequency matrix where each column appears to be a document.
trainMatrixModified = pd.read_table('trainMatrixModified.txt', sep='\t', header=None)

## Transpose Matrix
trainMatrixModified = trainMatrixModified.T

In [26]:
trainMatrixModified.head(5)

0     1     2     3     4     5     6     7     8     9     ...   5490  \
0   2.0   2.0   2.0   1.0   8.0   6.0   2.0   8.0   2.0   4.0  ...    0.0   
1   0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
2   0.0   0.0   0.0   1.0   0.0   0.0   0.0   2.0   0.0   1.0  ...    0.0   
3   2.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
4   2.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   

   5491  5492  5493  5494  5495  5496  5497  5498  5499  
0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[5 rows x 5500 columns]

In [27]:
## Read test term matrix (5500 terms, 200 documents)
## Term frequency matrix where each column appears to be a document.
testMatrixModified = pd.read_table('testMatrixModified.txt', sep='\t', header=None)

## Transpose Matrix
testMatrixModified = testMatrixModified.T

In [28]:
testMatrixModified.head(5)

0     1     2     3     4     5     6     7     8     9     ...   5490  \
0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0  ...    0.0   
1   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
2   1.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
3   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
4   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0  ...    0.0   

   5491  5492  5493  5494  5495  5496  5497  5498  5499  
0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[5 rows x 5500 columns]

In [52]:
## Read train and test classes
trainClasses = pd.read_table('trainClasses.txt', sep='\t', header=None)
trainClasses

0  1
0      0  0
1      1  1
2      2  0
3      3  1
4      4  0
5      5  1
6      6  1
7      7  1
8      8  1
9      9  1
10    10  1
11    11  0
12    12  0
13    13  1
14    14  1
15    15  1
16    16  0
17    17  0
18    18  1
19    19  0
20    20  0
21    21  1
22    22  0
23    23  1
24    24  1
25    25  0
26    26  1
27    27  1
28    28  1
29    29  1
..   ... ..
770  770  1
771  771  0
772  772  0
773  773  0
774  774  1
775  775  0
776  776  1
777  777  1
778  778  0
779  779  0
780  780  0
781  781  0
782  782  0
783  783  1
784  784  0
785  785  0
786  786  1
787  787  1
788  788  1
789  789  1
790  790  0
791  791  1
792  792  1
793  793  0
794  794  1
795  795  0
796  796  1
797  797  1
798  798  1
799  799  1

[800 rows x 2 columns]

In [49]:
testClasses = pd.read_table('testClasses.txt', sep='\t', header=None)
testClasses

0  1
0  0  1
1  1  0
2  2  0
3  3  1
4  4  1

In [50]:
## Read modified terms
modifiedTerms = pd.read_table('modifiedTerms.txt', sep='\t', header=None)
modifiedTerms

0
0                     david
1                       rex
2                      wood
3                   subject
4                      call
5                   librari
6                     creat
7                    widget
8                   multipl
9                      time
10                      dai
11                      ago
12                     post
13                 question
14                      try
15                 function
16                      set
17                      app
18                    point
19               xtappiniti
20                     help
21                     have
22                  problem
23                    littl
24                     test
25                  program
26                    close
27                    model
28                     real
29                   actual
...                     ...
5470               director
5471                overlap
5472                  twmrc
5473                   ctwm
5474                  utter
5475                leunggm
5476  odincontrolutorontoca
5477                  leung
5478                reclaim
5479                   cach
5480                 sussex
5481                  newli
5482              xtgetvalu
5483                   fuer
5484  xtcreatemanagedwidget
5485                 fulton
5486                attende
5487                   cose
5488                   icop
5489               csabuedu
5490                antonio
5491                   pera
5492            undoubtedli
5493               shortcut
5494                    ear
5495                  shear
5496                  handi
5497            inexperienc
5498                  markw
5499        pspmf3gpsemicom

[5500 rows x 1 columns]

In [29]:
## Create data frames to arrays
trainMatrixModifiedArray = np.array(trainMatrixModified)
testMatrixModifiedArray = np.array(testMatrixModified)

In [149]:
## Define a function for kNN search
## x = instance to be classified
## D = data matrix
## L = labels
## K = number of neighbors
## measure = euclidean or cosine (0 or 1)

def knn_search(x, D, L, K, measure):
    """ find K nearest neighbours of data point x among D """
    if measure == 0:
        # euclidean distances from the other points
        dists = np.sqrt(((D - x)**2).sum(axis=1))
    elif measure == 1:
        D_norm = np.array([np.linalg.norm(D[i]) for i in range(len(D))])
        x_norm = np.linalg.norm(x)
        sims = np.dot(D,x)/(D_norm * x_norm) ## cosine similarity
        dists = 1 - sims
    idx = np.argsort(dists) # sorting

    # return the indexes of K nearest neighbors
    return idx[:K], sorted(dists)[:K], round(np.array(L.iloc[:,[1]].T[idx[:K]]).mean())

In [233]:
## instance to be classified; read from testMatrixModified

## set index
i = 7

x = np.array(testMatrixModified.iloc[i])
x



array([0., 0., 0., ..., 0., 0., 0.])

In [234]:
# Finding the k=5 nearest neighbors using inverse of Cosine similarity as a distance metric
neigh_idx, distances, predictedClass = knn_search(x, trainMatrixModifiedArray, trainClasses, 15, 1)

In [235]:
## Index 
neigh_idx

array([602, 770, 354, 116, 715, 169, 448, 774, 416, 592, 182,  10, 541,
       290, 783], dtype=int64)

In [236]:
distances

[0.6745277225479404,
 0.674551922129925,
 0.7020873852283833,
 0.7053674186468871,
 0.7182702692756072,
 0.7199100801597353,
 0.7252991175890636,
 0.7269134364593515,
 0.7332301129567425,
 0.7332660050834415,
 0.7399800858665841,
 0.7411493338612172,
 0.7418836942593483,
 0.7424938286930244,
 0.7435803775182408]

In [237]:
trainMatrixModifiedArray[neigh_idx]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [238]:
predictedClass

1.0

In [239]:
## actual class
testClasses.iloc[[i],[1]]

1
7  1

In [240]:
predictedClass == testClasses.iloc[[i],[1]]

1
7  True

In [241]:
# Finding the k=5 nearest neighbors using inverse of Cosine similarity as a distance metric
neigh_idx2, distances, predictedClass = knn_search(x, trainMatrixModifiedArray, trainClasses, 15, 0)

In [242]:
## Index 
neigh_idx2

array([798, 757, 743,  38, 224, 706, 398, 119, 711,  69, 464, 615, 751,
       342, 551], dtype=int64)

In [243]:
predictedClass

0.0

In [244]:
## actual class
testClasses.iloc[[i],[1]]

1
7  1

In [245]:
predictedClass == testClasses.iloc[[i],[1]]

1
7  False

In [246]:
np.array(trainClasses.iloc[:,[1]].T[neigh_idx])

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int64)

In [247]:
np.array(trainClasses.iloc[:,[1]].T[neigh_idx2])

array([[1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0]], dtype=int64)

In [250]:
## Check length
len(testMatrixModified)

count = len(testMatrixModified)
i = 0
    
while i < count:
    print(i)
    i += 1

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199


In [297]:
## 1.b

## T = test matrix
## D = train matrix (array)
## L = labels (matrix)
## K = number of neighbors
## measure = euclidean or cosine (0 or 1)

def knn_accuracy(T, D, L, K, measure):

    matches = 0.00
    count = len(T)
    i = 0
    
    while i < count:
        
        neigh_idx, distances, predictedClass = knn_search(np.array(T.iloc[i]), D, L, K, measure)
        
        isMatch = predictedClass == L.iloc[[i],[1]]

        if isMatch.bool() == True:
            matches += 1
            
        i += 1
    
    # return accuracy measure
    return matches / count

In [298]:
knn_accuracy(testMatrixModified, trainMatrixModifiedArray, trainClasses, 15, 1)

0.495

In [299]:
knn_accuracy(testMatrixModified, trainMatrixModifiedArray, trainClasses, 15, 0)

0.465

In [300]:
knn_accuracy(testMatrixModified, trainMatrixModifiedArray, trainClasses, 5, 1)

0.5

In [301]:
knn_accuracy(testMatrixModified, trainMatrixModifiedArray, trainClasses, 5, 0)

0.495

In [302]:
knn_accuracy(testMatrixModified, trainMatrixModifiedArray, trainClasses, 9, 1)

0.505

In [303]:
knn_accuracy(testMatrixModified, trainMatrixModifiedArray, trainClasses, 9, 0)

0.48