In [28]:
## Michael Janke
## DSC478
## Assignment 3

from sklearn.cross_validation import KFold
from sklearn.linear_model import LinearRegression, Lasso, Ridge, ElasticNet, SGDRegressor
import numpy as np
import pandas as pd
import pylab as pl

from IPython.display import display
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [29]:
## 1.a - read in data

communityData = pd.read_csv('communities.csv', na_values=["?"])
communityData.head()

state        communityname  population  householdsize  racepctblack  \
0      8         Lakewoodcity        0.19           0.33          0.02   
1     53          Tukwilacity        0.00           0.16          0.12   
2     24         Aberdeentown        0.00           0.42          0.49   
3     34  Willingborotownship        0.04           0.77          1.00   
4     42    Bethlehemtownship        0.01           0.55          0.02   

   racePctWhite  racePctAsian  racePctHisp  agePct12t21  agePct12t29  \
0          0.90          0.12         0.17         0.34         0.47   
1          0.74          0.45         0.07         0.26         0.59   
2          0.56          0.17         0.04         0.39         0.47   
3          0.08          0.12         0.10         0.51         0.50   
4          0.95          0.09         0.05         0.38         0.38   

   agePct16t24  agePct65up  numbUrban  pctUrban  medIncome  pctWWage  \
0         0.29        0.32       0.20       1.0       0.37      0.72   
1         0.35        0.27       0.02       1.0       0.31      0.72   
2         0.28        0.32       0.00       0.0       0.30      0.58   
3         0.34        0.21       0.06       1.0       0.58      0.89   
4         0.23        0.36       0.02       0.9       0.50      0.72   

   pctWFarmSelf  pctWInvInc  pctWSocSec  pctWPubAsst  pctWRetire  medFamInc  \
0          0.34        0.60        0.29         0.15        0.43       0.39   
1          0.11        0.45        0.25         0.29        0.39       0.29   
2          0.19        0.39        0.38         0.40        0.84       0.28   
3          0.21        0.43        0.36         0.20        0.82       0.51   
4          0.16        0.68        0.44         0.11        0.71       0.46   

   perCapInc  whitePerCap  blackPerCap  indianPerCap  AsianPerCap  \
0       0.40         0.39         0.32          0.27         0.27   
1       0.37         0.38         0.33          0.16         0.30   
2       0.27         0.29         0.27          0.07         0.29   
3       0.36         0.40         0.39          0.16         0.25   
4       0.43         0.41         0.28          0.00         0.74   

   OtherPerCap  HispPerCap  NumUnderPov  PctPopUnderPov  PctLess9thGrade  \
0         0.36        0.41         0.08            0.19             0.10   
1         0.22        0.35         0.01            0.24             0.14   
2         0.28        0.39         0.01            0.27             0.27   
3         0.36        0.44         0.01            0.10             0.09   
4         0.51        0.48         0.00            0.06             0.25   

   PctNotHSGrad  PctBSorMore  PctUnemployed  PctEmploy  PctEmplManu  \
0          0.18         0.48           0.27       0.68         0.23   
1          0.24         0.30           0.27       0.73         0.57   
2          0.43         0.19           0.36       0.58         0.32   
3          0.25         0.31           0.33       0.71         0.36   
4          0.30         0.33           0.12       0.65         0.67   

   PctEmplProfServ  MalePctDivorce  MalePctNevMarr  FemalePctDiv  TotalPctDiv  \
0             0.41            0.68            0.40          0.75         0.75   
1             0.15            1.00            0.63          0.91         1.00   
2             0.29            0.63            0.41          0.71         0.70   
3             0.45            0.34            0.45          0.49         0.44   
4             0.38            0.22            0.27          0.20         0.21   

   PersPerFam  PctFam2Par  PctKids2Par  PctYoungKids2Par  PctTeen2Par  \
0        0.35        0.55         0.59              0.61         0.56   
1        0.29        0.43         0.47              0.60         0.39   
2        0.45        0.42         0.44              0.43         0.43   
3        0.75        0.65         0.54              0.83         0.65   
4        0.51        0.91         0.91              0.89         0

In [33]:
## Look for nulls

communityData.isnull().any()

state                    False
communityname            False
population               False
householdsize            False
racepctblack             False
racePctWhite             False
racePctAsian             False
racePctHisp              False
agePct12t21              False
agePct12t29              False
agePct16t24              False
agePct65up               False
numbUrban                False
pctUrban                 False
medIncome                False
pctWWage                 False
pctWFarmSelf             False
pctWInvInc               False
pctWSocSec               False
pctWPubAsst              False
pctWRetire               False
medFamInc                False
perCapInc                False
whitePerCap              False
blackPerCap              False
indianPerCap             False
AsianPerCap              False
OtherPerCap               True
HispPerCap               False
NumUnderPov              False
PctPopUnderPov           False
PctLess9thGrade          False
PctNotHS

In [34]:
## impute missing OtherPerCap
other_mean = communityData.OtherPerCap.mean()
communityData.OtherPerCap.fillna(other_mean, axis=0, inplace=True)

In [37]:
## recheck nulls
communityData.isnull().any().any()

False

In [38]:
communityData.describe()

state   population  householdsize  racepctblack  racePctWhite  \
count  1994.000000  1994.000000    1994.000000   1994.000000   1994.000000   
mean     28.683551     0.057593       0.463395      0.179629      0.753716   
std      16.397553     0.126906       0.163717      0.253442      0.244039   
min       1.000000     0.000000       0.000000      0.000000      0.000000   
25%      12.000000     0.010000       0.350000      0.020000      0.630000   
50%      34.000000     0.020000       0.440000      0.060000      0.850000   
75%      42.000000     0.050000       0.540000      0.230000      0.940000   
max      56.000000     1.000000       1.000000      1.000000      1.000000   

       racePctAsian  racePctHisp  agePct12t21  agePct12t29  agePct16t24  \
count   1994.000000  1994.000000  1994.000000  1994.000000  1994.000000   
mean       0.153681     0.144022     0.424218     0.493867     0.336264   
std        0.208877     0.232492     0.155196     0.143564     0.166505   
min        0.000000     0.000000     0.000000     0.000000     0.000000   
25%        0.040000     0.010000     0.340000     0.410000     0.250000   
50%        0.070000     0.040000     0.400000     0.480000     0.290000   
75%        0.170000     0.160000     0.470000     0.540000     0.360000   
max        1.000000     1.000000     1.000000     1.000000     1.000000   

        agePct65up    numbUrban     pctUrban    medIncome     pctWWage  \
count  1994.000000  1994.000000  1994.000000  1994.000000  1994.000000   
mean      0.423164     0.064072     0.696269     0.361123     0.558154   
std       0.179185     0.128256     0.444811     0.209362     0.182913   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.300000     0.000000     0.000000     0.200000     0.440000   
50%       0.420000     0.030000     1.000000     0.320000     0.560000   
75%       0.530000     0.070000     1.000000     0.490000     0.690000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

       pctWFarmSelf   pctWInvInc   pctWSocSec  pctWPubAsst   pctWRetire  \
count   1994.000000  1994.000000  1994.000000  1994.000000  1994.000000   
mean       0.291570     0.495687     0.471133     0.317778     0.479248   
std        0.204108     0.178071     0.173619     0.222137     0.167564   
min        0.000000     0.000000     0.000000     0.000000     0.000000   
25%        0.160000     0.370000     0.350000     0.142500     0.360000   
50%        0.230000     0.480000     0.475000     0.260000     0.470000   
75%        0.370000     0.620000     0.580000     0.440000     0.580000   
max        1.000000     1.000000     1.000000     1.000000     1.000000   

         medFamInc    perCapInc  whitePerCap  blackPerCap  indianPerCap  \
count  1994.000000  1994.000000  1994.000000  1994.000000   1994.000000   
mean      0.375677     0.350251     0.368049     0.291098      0.203506   
std       0.198257     0.191109     0.186804     0.171593      0.164775   
min       0.000000     0.000000     0.000000     0.000000      0.000000   
25%       0.230000     0.220000     0.240000     0.172500      0.110000   
50%       0.330000     0.300000     0.320000     0.250000      0.170000   
75%       0.480000     0.430000     0.440000     0.380000      0.250000   
max       1.000000     1.000000     1.000000     1.000000      1.000000   

       AsianPerCap  OtherPerCap   HispPerCap  NumUnderPov  PctPopUnderPov  \
count  1994.000000  1994.000000  1994.000000  1994.000000     1994.000000   
mean      0.322357     0.284742     0.386279     0.055507        0.303024   
std       0.195411     0.190960     0.183081     0.127941        0.228474   
min       0.000000     0.000000     0.000000     0.000000        0.000000   
25%       0.190000     0.170000     0.260000     0.010000        0.110000   
50%       0.280000     0.250000     0.345000     0.020000        0.250000   
75%       0.400000     0.360000     0.480000     0.050000        0.450000   

In [39]:
## extract independent variables

communityRecords = communityData[['population','householdsize','racepctblack','racePctWhite','racePctAsian','racePctHisp','agePct12t21','agePct12t29','agePct16t24','agePct65up','numbUrban','pctUrban','medIncome','pctWWage','pctWFarmSelf','pctWInvInc','pctWSocSec','pctWPubAsst','pctWRetire','medFamInc','perCapInc','whitePerCap','blackPerCap','indianPerCap','AsianPerCap','OtherPerCap','HispPerCap','NumUnderPov','PctPopUnderPov','PctLess9thGrade','PctNotHSGrad','PctBSorMore','PctUnemployed','PctEmploy','PctEmplManu','PctEmplProfServ','MalePctDivorce','MalePctNevMarr','FemalePctDiv','TotalPctDiv','PersPerFam','PctFam2Par','PctKids2Par','PctYoungKids2Par','PctTeen2Par','PctWorkMomYoungKids','PctWorkMom','NumIlleg','PctIlleg','NumImmig','PctImmigRecent','PctImmigRec5','PctImmigRec8','PctImmigRec10','PctRecentImmig','PctRecImmig5','PctRecImmig8','PctRecImmig10','PctSpeakEnglOnly','PctNotSpeakEnglWell','PctLargHouseFam','PctLargHouseOccup','PersPerOccupHous','PersPerOwnOccHous','PersPerRentOccHous','PctPersOwnOccup','PctPersDenseHous','PctHousLess3BR','MedNumBR','HousVacant','PctHousOccup','PctHousOwnOcc','PctVacantBoarded','PctVacMore6Mos','MedYrHousBuilt','PctHousNoPhone','PctWOFullPlumb','OwnOccLowQuart','OwnOccMedVal','OwnOccHiQuart','RentLowQ','RentMedian','RentHighQ','MedRent','MedRentPctHousInc','MedOwnCostPctInc','MedOwnCostPctIncNoMtg','NumInShelters','NumStreet','PctForeignBorn','PctBornSameState','PctSameHouse85','PctSameCity85','PctSameState85','LandArea','PopDens','PctUsePubTrans']]
communityRecords.head()

population  householdsize  racepctblack  racePctWhite  racePctAsian  \
0        0.19           0.33          0.02          0.90          0.12   
1        0.00           0.16          0.12          0.74          0.45   
2        0.00           0.42          0.49          0.56          0.17   
3        0.04           0.77          1.00          0.08          0.12   
4        0.01           0.55          0.02          0.95          0.09   

   racePctHisp  agePct12t21  agePct12t29  agePct16t24  agePct65up  numbUrban  \
0         0.17         0.34         0.47         0.29        0.32       0.20   
1         0.07         0.26         0.59         0.35        0.27       0.02   
2         0.04         0.39         0.47         0.28        0.32       0.00   
3         0.10         0.51         0.50         0.34        0.21       0.06   
4         0.05         0.38         0.38         0.23        0.36       0.02   

   pctUrban  medIncome  pctWWage  pctWFarmSelf  pctWInvInc  pctWSocSec  \
0       1.0       0.37      0.72          0.34        0.60        0.29   
1       1.0       0.31      0.72          0.11        0.45        0.25   
2       0.0       0.30      0.58          0.19        0.39        0.38   
3       1.0       0.58      0.89          0.21        0.43        0.36   
4       0.9       0.50      0.72          0.16        0.68        0.44   

   pctWPubAsst  pctWRetire  medFamInc  perCapInc  whitePerCap  blackPerCap  \
0         0.15        0.43       0.39       0.40         0.39         0.32   
1         0.29        0.39       0.29       0.37         0.38         0.33   
2         0.40        0.84       0.28       0.27         0.29         0.27   
3         0.20        0.82       0.51       0.36         0.40         0.39   
4         0.11        0.71       0.46       0.43         0.41         0.28   

   indianPerCap  AsianPerCap  OtherPerCap  HispPerCap  NumUnderPov  \
0          0.27         0.27         0.36        0.41         0.08   
1          0.16         0.30         0.22        0.35         0.01   
2          0.07         0.29         0.28        0.39         0.01   
3          0.16         0.25         0.36        0.44         0.01   
4          0.00         0.74         0.51        0.48         0.00   

   PctPopUnderPov  PctLess9thGrade  PctNotHSGrad  PctBSorMore  PctUnemployed  \
0            0.19             0.10          0.18         0.48           0.27   
1            0.24             0.14          0.24         0.30           0.27   
2            0.27             0.27          0.43         0.19           0.36   
3            0.10             0.09          0.25         0.31           0.33   
4            0.06             0.25          0.30         0.33           0.12   

   PctEmploy  PctEmplManu  PctEmplProfServ  MalePctDivorce  MalePctNevMarr  \
0       0.68         0.23             0.41            0.68            0.40   
1       0.73         0.57             0.15            1.00            0.63   
2       0.58         0.32             0.29            0.63            0.41   
3       0.71         0.36             0.45            0.34            0.45   
4       0.65         0.67             0.38            0.22            0.27   

   FemalePctDiv  TotalPctDiv  PersPerFam  PctFam2Par  PctKids2Par  \
0          0.75         0.75        0.35        0.55         0.59   
1          0.91         1.00        0.29        0.43         0.47   
2          0.71         0.70        0.45        0.42         0.44   
3          0.49         0.44        0.75        0.65         0.54   
4          0.20         0.21        0.51        0.91         0.91   

   PctYoungKids2Par  PctTeen2Par  PctWorkMomYoungKids  PctWorkMom  NumIlleg  \
0              0.61         0.56                 0.74        0.76      0.04   
1              0.60         0.39                 0.46        0.53      0.00   
2              0.43         0.43                 0.71        0.67      0.01   
3              0.83         0.65                 0.85        

In [40]:
## extract dependent variable

communityTarget = communityData[['ViolentCrimesPerPop']]
communityTarget.head()

ViolentCrimesPerPop
0                 0.20
1                 0.67
2                 0.43
3                 0.12
4                 0.03

In [41]:
## From Chapter 8 of Machine Learning in Action

def standRegres(xArr,yArr):
    xMat = mat(xArr); yMat = mat(yArr).T
    xTx = xMat.T*xMat
    if linalg.det(xTx) == 0.0:
        print "This matrix is singular, cannot do inverse"
        return
    ws = xTx.I * (xMat.T*yMat)
    return ws

In [65]:
## Convert data frames to arrays
# In order to do multiple regression we need to add a column of 1s for x0


from numpy import *

xArr = np.array([np.concatenate((x,[1.0])) for x in np.array(communityRecords, dtype=float)])
#xArr = np.array(communityRecords, dtype=float)
yArr = np.array(communityTarget, dtype=float)

xArr


array([[0.19, 0.33, 0.02, ..., 0.26, 0.2 , 1.  ],
       [0.  , 0.16, 0.12, ..., 0.12, 0.45, 1.  ],
       [0.  , 0.42, 0.49, ..., 0.21, 0.02, 1.  ],
       ...,
       [0.16, 0.37, 0.25, ..., 0.32, 0.18, 1.  ],
       [0.08, 0.51, 0.06, ..., 0.38, 0.33, 1.  ],
       [0.2 , 0.78, 0.14, ..., 0.3 , 0.05, 1.  ]])

In [66]:
yArr

array([[0.2 ],
       [0.67],
       [0.43],
       ...,
       [0.23],
       [0.19],
       [0.48]])

In [67]:
## Perform standard regression
ws = standRegres(xArr, yArr.T) # There's an awful lot of transposing going on :)

matrix([[ 1.31108068e-01],
        [-3.14114977e-02],
        [ 2.09909670e-01],
        [-4.05351612e-02],
        [-1.38892919e-02],
        [ 5.89726825e-02],
        [ 1.23399025e-01],
        [-2.22621600e-01],
        [-1.47500199e-01],
        [ 5.01635477e-02],
        [-2.42413829e-01],
        [ 4.64024392e-02],
        [-1.96945615e-01],
        [-2.06117500e-01],
        [ 4.65935490e-02],
        [-1.77212915e-01],
        [ 6.30148504e-02],
        [ 1.14942190e-02],
        [-9.08951848e-02],
        [ 2.74640044e-01],
        [ 1.01752476e-01],
        [-3.31517562e-01],
        [-2.91799268e-02],
        [-3.54483393e-02],
        [ 2.26173855e-02],
        [ 4.30950137e-02],
        [ 3.44408548e-02],
        [ 1.28412458e-01],
        [-1.91293360e-01],
        [-1.00769002e-01],
        [ 6.46856092e-02],
        [ 1.06062117e-01],
        [ 2.44125991e-06],
        [ 2.34984611e-01],
        [-3.75705330e-02],
        [-7.74957660e-03],
        [ 4.66779619e-01],
 

In [109]:
## Compute predicted values

xMat = mat(xArr)
yMat = mat(yArr)
yHat = xMat*ws

print type(yHat)
print yHat

yHat = np.array(yHat)
print type(yHat)
print yHat

<class 'numpy.matrixlib.defmatrix.matrix'>
[[0.16551838]
 [0.29062973]
 [0.38367799]
 ...
 [0.40142767]
 [0.16882645]
 [0.37326947]]
<type 'numpy.ndarray'>
[[0.16551838]
 [0.29062973]
 [0.38367799]
 ...
 [0.40142767]
 [0.16882645]
 [0.37326947]]


In [108]:
print type(yMat)

print yMat

yMat = np.array(yMat)
print type(yMat)

print yMat

<type 'numpy.ndarray'>
[[0.2 ]
 [0.67]
 [0.43]
 ...
 [0.23]
 [0.19]
 [0.48]]
<type 'numpy.ndarray'>
[[0.2 ]
 [0.67]
 [0.43]
 ...
 [0.23]
 [0.19]
 [0.48]]


In [110]:
corrcoef(yHat.T, yMat.T)

array([[1.        , 0.83294957],
       [0.83294957, 1.        ]])

In [136]:
## RMSE

err = np.squeeze(np.array(abs(yHat - yMat).T)) # https://stackoverflow.com/questions/3337301/numpy-matrix-to-array
print 'First 10 error values'
print err[:10]
print ''

# Dot product of error vector with itself gives us the sum of squared errors
total_error = np.dot(err,err)

print 'Total Error'
print total_error
print ''

# Compute RMSE
rmse = np.sqrt(total_error/len(yHat))
print 'RMSE'
print rmse

First 10 error values
[0.03448162 0.37937027 0.04632201 0.20270857 0.05129155 0.09017938
 0.05800201 0.1076608  0.29252029 0.14473903]

Total Error
33.12538681059086

RMSE
0.128889607797876


In [137]:
## Display regression coefficients
## First value is X0
ws

matrix([[ 1.31108068e-01],
        [-3.14114977e-02],
        [ 2.09909670e-01],
        [-4.05351612e-02],
        [-1.38892919e-02],
        [ 5.89726825e-02],
        [ 1.23399025e-01],
        [-2.22621600e-01],
        [-1.47500199e-01],
        [ 5.01635477e-02],
        [-2.42413829e-01],
        [ 4.64024392e-02],
        [-1.96945615e-01],
        [-2.06117500e-01],
        [ 4.65935490e-02],
        [-1.77212915e-01],
        [ 6.30148504e-02],
        [ 1.14942190e-02],
        [-9.08951848e-02],
        [ 2.74640044e-01],
        [ 1.01752476e-01],
        [-3.31517562e-01],
        [-2.91799268e-02],
        [-3.54483393e-02],
        [ 2.26173855e-02],
        [ 4.30950137e-02],
        [ 3.44408548e-02],
        [ 1.28412458e-01],
        [-1.91293360e-01],
        [-1.00769002e-01],
        [ 6.46856092e-02],
        [ 1.06062117e-01],
        [ 2.44125991e-06],
        [ 2.34984611e-01],
        [-3.75705330e-02],
        [-7.74957660e-03],
        [ 4.66779619e-01],
 

In [146]:
# Now let's compute RMSE using 10-fold x-validation

# Create linear regression object
linreg = LinearRegression()

n = 10
kf = KFold(len(xArr), n_folds=n)
xval_err = 0
for train,test in kf:
    linreg.fit(xArr,yArr)
    p = linreg.predict(xArr)
    
    #np.squeeze(np.array(abs(yHat - yMat).T))
    
    e = np.squeeze(p-yArr)
    xval_err += np.sqrt(np.dot(e,e)/len(xArr))
       
rmse_10cv = xval_err/n

In [147]:
print('RMSE on standard linear regression: %.4f' %rmse)
print('RMSE on 10-fold CV: %.4f' %rmse_10cv)

RMSE on standard linear regression: 0.1289
RMSE on 10-fold CV: 0.1289


In [148]:
## Revisit 2B above. I did not expect identical values. Text does not show how to calculate RMSE so my attempt may not be correct.