In [33]:
# Michael Janke
# DSC 478
# Assignment 4

In [34]:
import numpy as np
import pylab as pl
import pandas as pd
from sklearn.cluster import KMeans 
from sklearn import preprocessing

np.set_printoptions(precision=2, linewidth=500, suppress=True, threshold=np.nan)

from IPython.display import display
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [35]:
## 1.a load data

## Rows = images
## Columns = features

data = pd.read_csv('segmentation_data.txt', header=None)
classes = pd.read_table('segmentation_classes.txt', sep='\t', header=None)

In [36]:
data.head(10)

0      1   2         3    4         5         6         7         8   \
0  110.0  189.0   9  0.000000  0.0  1.000000  0.666667  1.222222  1.186342   
1   86.0  187.0   9  0.000000  0.0  1.111111  0.720082  1.444444  0.750309   
2  225.0  244.0   9  0.000000  0.0  3.388889  2.195113  3.000000  1.520234   
3   47.0  232.0   9  0.000000  0.0  1.277778  1.254621  1.000000  0.894427   
4   97.0  186.0   9  0.000000  0.0  1.166667  0.691215  1.166667  1.005540   
5  157.0  221.0   9  0.000000  0.0  1.055556  0.646930  1.222222  0.620633   
6   62.0  224.0   9  0.000000  0.0  0.944445  1.083547  2.333333  1.632993   
7   27.0  248.0   9  0.111111  0.0  1.611111  0.646930  3.166667  1.722401   
8   44.0  233.0   9  0.000000  0.0  2.222222  2.146487  2.111111  1.327766   
9   17.0  229.0   9  0.000000  0.0  2.111111  1.985130  2.444445  1.614747   

          9          10         11         12        13         14         15  \
0  12.925926  10.888889   9.222222  18.666668 -6.111111 -11.111111  17.222221   
1  13.740741  11.666667  10.333334  19.222221 -6.222222 -10.222222  16.444445   
2  12.259259  10.333334   9.333334  17.111110 -5.777778  -8.777778  14.555555   
3  12.703704  11.000000   9.000000  18.111110 -5.111111 -11.111111  16.222221   
4  15.592592  13.888889  11.777778  21.111110 -5.111111 -11.444445  16.555555   
5  12.111111  10.222222   8.111112  18.000000 -5.666666 -12.000000  17.666666   
6  14.629630  13.222222  11.444445  19.222221 -4.222222  -9.555555  13.777778   
7  15.296296  14.777778  12.888889  18.222221 -1.555556  -7.222222   8.777778   
8  14.481482  12.555555  11.333333  19.555555 -5.777778  -9.444445  15.222222   
9  13.703704  11.222222  11.111111  18.777779 -7.444445  -7.777778  15.222222   

          16        17        18  
0  18.666668  0.508139  1.910864  
1  19.222221  0.463329  1.941465  
2  17.111110  0.480149  1.987902  
3  18.111110  0.500966  1.875362  
4  21.111110  0.442661  1.863654  
5  18.000000  0.549180  1.877146  
6  19.222221  0.408965  1.860191  
7  18.222221  0.312227  1.783512  
8  19.555555  0.422174  1.950405  
9  18.777779  0.439852  2.099904

In [37]:
classes.head(10)

0  1
0  GRASS  0
1  GRASS  0
2  GRASS  0
3  GRASS  0
4  GRASS  0
5  GRASS  0
6  GRASS  0
7  GRASS  0
8  GRASS  0
9  GRASS  0

In [38]:
## 1.a Perform Min-Max Normalization

min_max_scaler = preprocessing.MinMaxScaler().fit(data)
data_norm = min_max_scaler.transform(data)

data_norm[0:5]

array([[0.43, 0.74, 0.  , 0.  , 0.  , 0.03, 0.  , 0.03, 0.  , 0.09, 0.08, 0.06, 0.13, 0.73, 0.01, 0.87, 0.12, 0.51, 0.83],
       [0.34, 0.73, 0.  , 0.  , 0.  , 0.04, 0.  , 0.03, 0.  , 0.1 , 0.09, 0.07, 0.13, 0.73, 0.02, 0.86, 0.13, 0.46, 0.84],
       [0.89, 0.97, 0.  , 0.  , 0.  , 0.12, 0.  , 0.07, 0.  , 0.09, 0.08, 0.06, 0.12, 0.74, 0.04, 0.83, 0.11, 0.48, 0.84],
       [0.18, 0.92, 0.  , 0.  , 0.  , 0.04, 0.  , 0.02, 0.  , 0.09, 0.08, 0.06, 0.13, 0.75, 0.01, 0.86, 0.12, 0.5 , 0.83],
       [0.38, 0.73, 0.  , 0.  , 0.  , 0.04, 0.  , 0.03, 0.  , 0.11, 0.1 , 0.08, 0.15, 0.75, 0.01, 0.86, 0.14, 0.44, 0.82]])

In [39]:
## 1.b perfrom Kmeans clustering

kmeans = KMeans(n_clusters=7, max_iter=500, verbose=1) # initialization
kmeans.fit(data_norm)

Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 392.4193986215183
start iteration
done sorting
end inner loop
Iteration 1, inertia 371.7905494812884
start iteration
done sorting
end inner loop
Iteration 2, inertia 366.5654250860906
start iteration
done sorting
end inner loop
Iteration 3, inertia 365.268224901658
start iteration
done sorting
end inner loop
Iteration 4, inertia 363.66857482628814
start iteration
done sorting
end inner loop
Iteration 5, inertia 362.2928249681312
start iteration
done sorting
end inner loop
Iteration 6, inertia 359.7573254851099
start iteration
done sorting
end inner loop
Iteration 7, inertia 356.5997811968218
start iteration
done sorting
end inner loop
Iteration 8, inertia 354.4734398533888
start iteration
done sorting
end inner loop
Iteration 9, inertia 353.47703380846747
start iteration
done sorting
end inner loop
Iteration 10, inertia 352.2775043704115
start iteration
done sorting
end inner loop
Iteration 11, ine

end inner loop
Iteration 9, inertia 384.10232695294576
start iteration
done sorting
end inner loop
Iteration 10, inertia 382.145836752698
start iteration
done sorting
end inner loop
Iteration 11, inertia 378.1527649591835
start iteration
done sorting
end inner loop
Iteration 12, inertia 373.47434034272374
start iteration
done sorting
end inner loop
Iteration 13, inertia 371.4629086101302
start iteration
done sorting
end inner loop
Iteration 14, inertia 370.9963341840071
start iteration
done sorting
end inner loop
Iteration 15, inertia 370.7595603405245
start iteration
done sorting
end inner loop
Iteration 16, inertia 370.7310002545656
start iteration
done sorting
end inner loop
Iteration 17, inertia 370.72633305088374
start iteration
done sorting
end inner loop
Iteration 18, inertia 370.72633305088374
center shift 0.000000e+00 within tolerance 4.150157e-06
Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 392.49560975445115
start iteration
done so

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=500,
    n_clusters=7, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=1)

In [40]:
clusters = kmeans.predict(data_norm)

In [41]:
clusters

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 0, 4, 4, 4, 4, 0, 0, 4, 4, 4, 4, 4, 4, 4, 0, 4, 4, 4, 4, 0, 4, 0, 4, 0, 4, 4, 4, 4, 4, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 4, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 4, 4, 4, 4, 4, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 4, 4, 4, 4, 0, 4, 0, 4, 4, 4, 0, 0, 0, 4, 0, 4, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 4, 4, 0, 4, 0, 0, 4, 1, 4, 0, 4, 0, 4, 0, 0, 0, 5, 0, 0, 4, 4, 0, 0, 0, 0, 4, 0, 4, 4, 0, 4, 4, 4, 0, 0, 0, 4, 5, 4, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4, 5, 0, 0, 0, 5, 0, 4, 0, 4, 4, 0, 0, 0, 4, 0, 5, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 0, 4, 4, 0, 4, 5, 0, 0, 4, 0, 0, 0, 4, 0, 5, 4,
  

In [42]:
centroids = kmeans.cluster_centers_

In [43]:
# 1.b print centroids

centroids

array([[0.3 , 0.53, 0.  , 0.05, 0.05, 0.1 , 0.01, 0.08, 0.01, 0.4 , 0.37, 0.47, 0.35, 0.5 , 0.57, 0.21, 0.47, 0.3 , 0.16],
       [0.77, 0.43, 0.  , 0.01, 0.02, 0.04, 0.  , 0.02, 0.  , 0.04, 0.03, 0.06, 0.03, 0.78, 0.22, 0.49, 0.06, 0.54, 0.24],
       [0.54, 0.15, 0.  , 0.03, 0.  , 0.03, 0.  , 0.03, 0.  , 0.82, 0.78, 0.89, 0.79, 0.27, 0.67, 0.29, 0.89, 0.21, 0.13],
       [0.51, 0.81, 0.  , 0.08, 0.01, 0.05, 0.  , 0.05, 0.  , 0.11, 0.09, 0.09, 0.14, 0.68, 0.08, 0.82, 0.13, 0.41, 0.89],
       [0.75, 0.53, 0.  , 0.04, 0.04, 0.11, 0.02, 0.11, 0.02, 0.3 , 0.28, 0.35, 0.26, 0.59, 0.45, 0.31, 0.35, 0.3 , 0.16],
       [0.25, 0.39, 0.  , 0.08, 0.02, 0.08, 0.  , 0.06, 0.01, 0.15, 0.14, 0.18, 0.12, 0.72, 0.34, 0.35, 0.18, 0.41, 0.2 ],
       [0.25, 0.46, 0.  , 0.03, 0.01, 0.04, 0.  , 0.03, 0.  , 0.03, 0.02, 0.04, 0.02, 0.77, 0.22, 0.51, 0.04, 0.8 , 0.18]])

In [44]:
# 1.b completeness and homogeneity

from sklearn.metrics import completeness_score, homogeneity_score

In [45]:
cs = completeness_score(classes[1],clusters)
print cs

0.611674499991089


In [46]:
hs = homogeneity_score(classes[1],clusters)
print hs

0.609965639314724


In [55]:
# 1.c Perform PCA

from sklearn import decomposition
pca = decomposition.PCA(n_components=6)

data_trans = pca.fit(data_norm).transform(data_norm)
#print data_trans

In [48]:
# six components explain 95% of the variance

print(pca.explained_variance_ratio_)

[0.61 0.13 0.1  0.05 0.04 0.02]


In [49]:
# 1.c Perform kmeans on reduced dimensions

kmeans = KMeans(n_clusters=7, max_iter=500, verbose=1) # initialization
kmeans.fit(data_trans)

Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 313.6846442640539
start iteration
done sorting
end inner loop
Iteration 1, inertia 296.64717607402173
start iteration
done sorting
end inner loop
Iteration 2, inertia 292.5157919248556
start iteration
done sorting
end inner loop
Iteration 3, inertia 290.9791082887939
start iteration
done sorting
end inner loop
Iteration 4, inertia 288.6550809013142
start iteration
done sorting
end inner loop
Iteration 5, inertia 286.9559817948078
start iteration
done sorting
end inner loop
Iteration 6, inertia 284.16912715369034
start iteration
done sorting
end inner loop
Iteration 7, inertia 278.23656215877867
start iteration
done sorting
end inner loop
Iteration 8, inertia 275.9061773936171
start iteration
done sorting
end inner loop
Iteration 9, inertia 275.7578229826482
start iteration
done sorting
end inner loop
Iteration 10, inertia 275.7417869845417
start iteration
done sorting
end inner loop
Iteration 11, i

Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 316.60186648449564
start iteration
done sorting
end inner loop
Iteration 1, inertia 295.94817098615897
start iteration
done sorting
end inner loop
Iteration 2, inertia 293.4039565704349
start iteration
done sorting
end inner loop
Iteration 3, inertia 292.7856689130632
start iteration
done sorting
end inner loop
Iteration 4, inertia 292.48779762254696
start iteration
done sorting
end inner loop
Iteration 5, inertia 292.2842367248931
start iteration
done sorting
end inner loop
Iteration 6, inertia 292.1933297200202
start iteration
done sorting
end inner loop
Iteration 7, inertia 292.0727824640185
start iteration
done sorting
end inner loop
Iteration 8, inertia 291.9197765457502
start iteration
done sorting
end inner loop
Iteration 9, inertia 291.8746426759902
start iteration
done sorting
end inner loop
Iteration 10, inertia 291.8436176096551
start iteration
done sorting
end inner loop
Iteration 11, i

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=500,
    n_clusters=7, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=1)

In [50]:
clusters_pca = kmeans.predict(data_trans)
clusters_pca

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 6, 0, 0, 0, 0, 6, 6, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 6, 0, 6, 0, 6, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 6, 0, 6, 0, 0, 0, 6, 6, 6, 0, 6, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 6, 0, 0, 6, 0, 6, 6, 0, 2, 0, 6, 0, 6, 0, 6, 6, 6, 3, 6, 6, 0, 0, 6, 6, 6, 6, 0, 6, 0, 0, 6, 0, 0, 0, 6, 6, 6, 0, 3, 0, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 3, 6, 6, 6, 3, 6, 0, 6, 0, 0, 6, 6, 6, 0, 6, 3, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 6, 0, 0, 6, 0, 3, 6, 6, 0, 6, 6, 6, 0, 6, 3, 0,
  

In [51]:
centroids_pca = kmeans.cluster_centers_
centroids_pca

array([[ 0.18,  0.05, -0.27,  0.19,  0.03,  0.02],
       [ 1.41,  0.09,  0.04, -0.17, -0.03, -0.01],
       [-0.51, -0.07, -0.34, -0.07,  0.08,  0.01],
       [-0.2 , -0.24,  0.15,  0.06,  0.14, -0.01],
       [-0.6 , -0.36,  0.11, -0.13, -0.13, -0.02],
       [-0.62,  0.64,  0.2 , -0.09, -0.07,  0.01],
       [ 0.44, -0.11,  0.17,  0.24, -0.05, -0.01]])

In [52]:
cs_pca = completeness_score(classes[1],clusters_pca)
print cs_pca

0.612438264931692


In [53]:
hs_pca = homogeneity_score(classes[1],clusters_pca)
print hs_pca

0.6107159652833897


In [54]:
# 1.e discuss

# Scores for full data
print 'Completeness Score = ' + str(cs)
print 'Homogeneity Score = ' + str(hs)
print '\n'
# Scores after PCA
print 'Completeness Score = ' + str(cs_pca)
print 'Homogeneity Score = ' + str(hs_pca)

Completeness Score = 0.611674499991089
Homogeneity Score = 0.609965639314724


Completeness Score = 0.612438264931692
Homogeneity Score = 0.6107159652833897


The scores before and after PCA are essentially the same. This illustrates that the performance of a model can remain unchanged when utilizing PCA to reduce dimensionality. PCA only retains those features that provide value to the model.

***************************************************************************************************

In [23]:
# 2

# Note, my edits to the functions test and print_most_similar_jokes were done
# in the source file, itemBasedRec.py. The file has been included with submission

import itemBasedRec as ibr
reload(ibr)

<module 'itemBasedRec' from 'itemBasedRec.pyc'>

In [56]:
# 2.a load data
dataMat = np.genfromtxt('modified_jester_data.csv',delimiter=',')
#dataMat

In [57]:
jokes = ibr.load_jokes('jokes.csv')
#jokes

In [26]:
# 2.b standEst MAE
ibr.test(dataMat, 0.2, ibr.standEst)

Mean Absoloute Error for standEst : 3.6902082953022366


In [27]:
# 2.b svdEst MAE
ibr.test(dataMat, 0.2, ibr.svdEst)

Mean Absoloute Error for svdEst : 3.7162536330000306


In [32]:
# 2.c print most similar jokes
ibr.print_most_similar_jokes(dataMat, jokes, 22, 5, ibr.pearsSim)

Selected joke: 

Q: What is the Australian word for a boomerang that won't   come back? A: A stick 

Top 5 Recommended jokes are: 

A country guy goes into a city bar that has a dress code and the maitred' demands he wear a tie. Discouraged the guy goes to his car to sulk when inspiration strikes: He's got jumper cables in the trunk! So he wraps them around his neck sort of like a string tie (a bulky string tie to be sure) and returns to the bar. The maitre d' is reluctant but says to the guy "Okay you're a pretty resourceful fellow you can come in... but just don't start anything"!
_______________
Q: What's the difference between a Lawyer and a Plumber? A: A Plumber works to unclog the system.
_______________
What did the Buddhist say to the hot dog vendor?Make me one with everything.
_______________
Q. What's 200 feet long and has 4 teeth? A. The front row at a Willie Nelson Concert.
_______________
The Chukcha (Russian Eskimo) phones up the Russian Parliament Building.  A guard answ