In [7]:
import numpy as np
import pylab as pl
import pandas as pd
from sklearn.cluster import KMeans 
from sklearn import preprocessing

np.set_printoptions(precision=2, linewidth=500, suppress=True, threshold=np.nan)

from IPython.display import display
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [8]:
## 1.a load data

## Rows = images
## Columns = features

data = pd.read_csv('segmentation_data.txt', header=None)
classes = pd.read_table('segmentation_classes.txt', sep='\t', header=None)

In [9]:
data.head(10)

0      1   2         3    4         5         6         7         8   \
0  110.0  189.0   9  0.000000  0.0  1.000000  0.666667  1.222222  1.186342   
1   86.0  187.0   9  0.000000  0.0  1.111111  0.720082  1.444444  0.750309   
2  225.0  244.0   9  0.000000  0.0  3.388889  2.195113  3.000000  1.520234   
3   47.0  232.0   9  0.000000  0.0  1.277778  1.254621  1.000000  0.894427   
4   97.0  186.0   9  0.000000  0.0  1.166667  0.691215  1.166667  1.005540   
5  157.0  221.0   9  0.000000  0.0  1.055556  0.646930  1.222222  0.620633   
6   62.0  224.0   9  0.000000  0.0  0.944445  1.083547  2.333333  1.632993   
7   27.0  248.0   9  0.111111  0.0  1.611111  0.646930  3.166667  1.722401   
8   44.0  233.0   9  0.000000  0.0  2.222222  2.146487  2.111111  1.327766   
9   17.0  229.0   9  0.000000  0.0  2.111111  1.985130  2.444445  1.614747   

          9          10         11         12        13         14         15  \
0  12.925926  10.888889   9.222222  18.666668 -6.111111 -11.111111  17.222221   
1  13.740741  11.666667  10.333334  19.222221 -6.222222 -10.222222  16.444445   
2  12.259259  10.333334   9.333334  17.111110 -5.777778  -8.777778  14.555555   
3  12.703704  11.000000   9.000000  18.111110 -5.111111 -11.111111  16.222221   
4  15.592592  13.888889  11.777778  21.111110 -5.111111 -11.444445  16.555555   
5  12.111111  10.222222   8.111112  18.000000 -5.666666 -12.000000  17.666666   
6  14.629630  13.222222  11.444445  19.222221 -4.222222  -9.555555  13.777778   
7  15.296296  14.777778  12.888889  18.222221 -1.555556  -7.222222   8.777778   
8  14.481482  12.555555  11.333333  19.555555 -5.777778  -9.444445  15.222222   
9  13.703704  11.222222  11.111111  18.777779 -7.444445  -7.777778  15.222222   

          16        17        18  
0  18.666668  0.508139  1.910864  
1  19.222221  0.463329  1.941465  
2  17.111110  0.480149  1.987902  
3  18.111110  0.500966  1.875362  
4  21.111110  0.442661  1.863654  
5  18.000000  0.549180  1.877146  
6  19.222221  0.408965  1.860191  
7  18.222221  0.312227  1.783512  
8  19.555555  0.422174  1.950405  
9  18.777779  0.439852  2.099904

In [10]:
classes.head(10)

0  1
0  GRASS  0
1  GRASS  0
2  GRASS  0
3  GRASS  0
4  GRASS  0
5  GRASS  0
6  GRASS  0
7  GRASS  0
8  GRASS  0
9  GRASS  0

In [11]:
## 1.a Perform Min-Max Normalization

min_max_scaler = preprocessing.MinMaxScaler().fit(data)
data_norm = min_max_scaler.transform(data)


data_norm[0:5]

array([[0.43, 0.74, 0.  , 0.  , 0.  , 0.03, 0.  , 0.03, 0.  , 0.09, 0.08, 0.06, 0.13, 0.73, 0.01, 0.87, 0.12, 0.51, 0.83],
       [0.34, 0.73, 0.  , 0.  , 0.  , 0.04, 0.  , 0.03, 0.  , 0.1 , 0.09, 0.07, 0.13, 0.73, 0.02, 0.86, 0.13, 0.46, 0.84],
       [0.89, 0.97, 0.  , 0.  , 0.  , 0.12, 0.  , 0.07, 0.  , 0.09, 0.08, 0.06, 0.12, 0.74, 0.04, 0.83, 0.11, 0.48, 0.84],
       [0.18, 0.92, 0.  , 0.  , 0.  , 0.04, 0.  , 0.02, 0.  , 0.09, 0.08, 0.06, 0.13, 0.75, 0.01, 0.86, 0.12, 0.5 , 0.83],
       [0.38, 0.73, 0.  , 0.  , 0.  , 0.04, 0.  , 0.03, 0.  , 0.11, 0.1 , 0.08, 0.15, 0.75, 0.01, 0.86, 0.14, 0.44, 0.82]])

In [12]:
## 1.b perfrom Kmeans clustering

kmeans = KMeans(n_clusters=7, max_iter=500, verbose=1) # initialization
kmeans.fit(data_norm)

Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 401.5504365272629
start iteration
done sorting
end inner loop
Iteration 1, inertia 386.9271712410003
start iteration
done sorting
end inner loop
Iteration 2, inertia 379.6893559842103
start iteration
done sorting
end inner loop
Iteration 3, inertia 374.26876379249796
start iteration
done sorting
end inner loop
Iteration 4, inertia 367.597341789224
start iteration
done sorting
end inner loop
Iteration 5, inertia 359.17217331485034
start iteration
done sorting
end inner loop
Iteration 6, inertia 354.60538114472513
start iteration
done sorting
end inner loop
Iteration 7, inertia 353.13194800673296
start iteration
done sorting
end inner loop
Iteration 8, inertia 351.87700393143814
start iteration
done sorting
end inner loop
Iteration 9, inertia 351.38339270374115
start iteration
done sorting
end inner loop
Iteration 10, inertia 351.3362342597593
start iteration
done sorting
end inner loop
Iteration 11,

Iteration 11, inertia 364.91756974309817
start iteration
done sorting
end inner loop
Iteration 12, inertia 364.91756974309817
center shift 0.000000e+00 within tolerance 4.150157e-06
Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 382.80749916154
start iteration
done sorting
end inner loop
Iteration 1, inertia 354.69464403130144
start iteration
done sorting
end inner loop
Iteration 2, inertia 350.6689996278186
start iteration
done sorting
end inner loop
Iteration 3, inertia 350.1181931713521
start iteration
done sorting
end inner loop
Iteration 4, inertia 350.04440331247935
start iteration
done sorting
end inner loop
Iteration 5, inertia 350.01207974106956
start iteration
done sorting
end inner loop
Iteration 6, inertia 350.01207974106956
center shift 0.000000e+00 within tolerance 4.150157e-06
Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 403.1047454378971
start iteration
done sorting
end inner loop
Iter

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=500,
    n_clusters=7, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=1)

In [13]:
clusters = kmeans.predict(data_norm)

In [14]:
clusters

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 0, 4, 4, 4, 4, 0, 0, 4, 4, 4, 4, 4, 4, 4, 0, 4, 4, 4, 4, 0, 4, 0, 4, 0, 4, 4, 4, 4, 4, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 4, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 4, 4, 4, 4, 4, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 4, 4, 4, 4, 0, 4, 0, 4, 4, 4, 0, 0, 0, 4, 0, 4, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 4, 4, 0, 4, 0, 0, 4, 1, 4, 0, 4, 0, 4, 0, 0, 0, 5, 0, 0, 4, 4, 0, 0, 0, 0, 4, 0, 4, 4, 0, 4, 4, 4, 0, 0, 0, 4, 5, 4, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4, 5, 0, 0, 0, 5, 0, 4, 0, 4, 4, 0, 0, 0, 4, 0, 5, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 0, 4, 4, 0, 4, 5, 0, 0, 4, 0, 0, 0, 4, 0, 5, 4,
  

In [15]:
centroids = kmeans.cluster_centers_

In [16]:
# 1.b print centroids

centroids

array([[0.3 , 0.53, 0.  , 0.05, 0.05, 0.1 , 0.01, 0.08, 0.01, 0.4 , 0.37, 0.47, 0.35, 0.5 , 0.57, 0.21, 0.47, 0.3 , 0.16],
       [0.77, 0.43, 0.  , 0.01, 0.02, 0.04, 0.  , 0.02, 0.  , 0.04, 0.04, 0.06, 0.03, 0.78, 0.22, 0.49, 0.06, 0.54, 0.24],
       [0.54, 0.15, 0.  , 0.03, 0.  , 0.03, 0.  , 0.03, 0.  , 0.82, 0.78, 0.89, 0.79, 0.27, 0.67, 0.29, 0.89, 0.21, 0.13],
       [0.51, 0.81, 0.  , 0.08, 0.01, 0.05, 0.  , 0.05, 0.  , 0.11, 0.09, 0.09, 0.14, 0.68, 0.08, 0.82, 0.13, 0.41, 0.89],
       [0.75, 0.53, 0.  , 0.04, 0.04, 0.11, 0.02, 0.11, 0.02, 0.3 , 0.28, 0.35, 0.27, 0.59, 0.45, 0.31, 0.35, 0.3 , 0.16],
       [0.26, 0.39, 0.  , 0.07, 0.02, 0.08, 0.  , 0.06, 0.  , 0.15, 0.14, 0.19, 0.12, 0.72, 0.34, 0.36, 0.19, 0.41, 0.2 ],
       [0.25, 0.46, 0.  , 0.03, 0.01, 0.04, 0.  , 0.03, 0.  , 0.03, 0.02, 0.04, 0.02, 0.77, 0.22, 0.51, 0.04, 0.8 , 0.18]])

In [17]:
# 1.b completeness and homogeneity

from sklearn.metrics import completeness_score, homogeneity_score

In [30]:
print completeness_score(classes[1],clusters)

0.6131870124853012


In [31]:
print homogeneity_score(classes[1],clusters)

0.6115021163370863


In [36]:
# 1.c Perform PCA

from sklearn import decomposition
pca = decomposition.PCA(n_components=6)

data_trans = pca.fit(data_norm).transform(data_norm)
print data_trans

[[-0.69  0.53  0.25 -0.2  -0.08  0.05]
 [-0.67  0.51  0.34 -0.17 -0.04  0.06]
 [-0.71  0.77 -0.16 -0.01 -0.17  0.04]
 [-0.73  0.51  0.5  -0.06 -0.14  0.03]
 [-0.64  0.53  0.3  -0.18 -0.02  0.05]
 [-0.73  0.63  0.08 -0.14 -0.17  0.02]
 [-0.67  0.53  0.44 -0.02 -0.06  0.03]
 [-0.66  0.52  0.59  0.15  0.01 -0.17]
 [-0.69  0.53  0.52 -0.01 -0.1   0.05]
 [-0.69  0.5   0.62 -0.02 -0.12  0.06]
 [-0.73  0.52  0.56 -0.01 -0.15  0.04]
 [-0.68  0.51  0.47 -0.04 -0.02 -0.15]
 [-0.72  0.59  0.15 -0.16 -0.14  0.05]
 [-0.69  0.52  0.32 -0.19 -0.08  0.05]
 [-0.77  0.77 -0.23 -0.07 -0.23 -0.19]
 [-0.72  0.5   0.45 -0.08 -0.12  0.04]
 [-0.74  0.57  0.11 -0.19 -0.14  0.02]
 [-0.66  0.42  0.58 -0.15 -0.    0.05]
 [-0.53  0.79 -0.23 -0.18  0.02  0.05]
 [-0.61  0.74 -0.16 -0.22 -0.01 -0.15]
 [-0.71  0.52  0.37 -0.15 -0.12  0.06]
 [-0.68  0.66 -0.02 -0.16 -0.13  0.09]
 [-0.67  0.59  0.38 -0.04 -0.07 -0.15]
 [-0.7   0.71  0.1  -0.03 -0.14 -0.15]
 [-0.64  0.69  0.27  0.03 -0.12  0.05]
 [-0.62  0.48  0.5  -0.1 

In [37]:
# six components explain 95% of the variance

print(pca.explained_variance_ratio_)

[0.61 0.13 0.1  0.05 0.04 0.02]


In [38]:
# 1.c Perform kmeans on reduced dimensions

kmeans = KMeans(n_clusters=7, max_iter=500, verbose=1) # initialization
kmeans.fit(data_trans)

Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 292.679565464377
start iteration
done sorting
end inner loop
Iteration 1, inertia 287.5471890649488
start iteration
done sorting
end inner loop
Iteration 2, inertia 285.8287388331077
start iteration
done sorting
end inner loop
Iteration 3, inertia 285.15576948138994
start iteration
done sorting
end inner loop
Iteration 4, inertia 284.9470949401468
start iteration
done sorting
end inner loop
Iteration 5, inertia 284.81468367460343
start iteration
done sorting
end inner loop
Iteration 6, inertia 284.7538526552896
start iteration
done sorting
end inner loop
Iteration 7, inertia 284.68756508741063
start iteration
done sorting
end inner loop
Iteration 8, inertia 284.6358287486619
start iteration
done sorting
end inner loop
Iteration 9, inertia 284.60334447102696
start iteration
done sorting
end inner loop
Iteration 10, inertia 284.59771996640006
start iteration
done sorting
end inner loop
Iteration 11, 

Iteration 6, inertia 256.83319149238537
center shift 3.089539e-03 within tolerance 1.236861e-05
Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 310.6998779822785
start iteration
done sorting
end inner loop
Iteration 1, inertia 290.21564235359983
start iteration
done sorting
end inner loop
Iteration 2, inertia 272.82081889783115
start iteration
done sorting
end inner loop
Iteration 3, inertia 263.5030310817217
start iteration
done sorting
end inner loop
Iteration 4, inertia 260.87011756445844
start iteration
done sorting
end inner loop
Iteration 5, inertia 259.801831340324
start iteration
done sorting
end inner loop
Iteration 6, inertia 258.44323296601203
start iteration
done sorting
end inner loop
Iteration 7, inertia 257.7786361914838
start iteration
done sorting
end inner loop
Iteration 8, inertia 257.6657783017087
start iteration
done sorting
end inner loop
Iteration 9, inertia 257.62654640313696
start iteration
done sorting
end inner loop
It

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=500,
    n_clusters=7, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=1)

In [40]:
clusters_pca = kmeans.predict(data_trans)
clusters_pca

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 5, 0, 0, 0, 0, 5, 5, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 5, 0, 5, 0, 5, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 5, 0, 5, 0, 0, 0, 5, 5, 5, 0, 5, 0, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 0, 0, 5, 0, 5, 5, 0, 6, 0, 5, 0, 5, 0, 5, 5, 5, 4, 5, 5, 0, 0, 5, 5, 5, 5, 0, 5, 0, 0, 5, 0, 0, 0, 5, 5, 5, 0, 4, 0, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 4, 5, 5, 5, 4, 5, 0, 5, 0, 0, 5, 5, 5, 0, 5, 4, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 5, 0, 0, 5, 0, 4, 5, 5, 0, 5, 5, 5, 0, 5, 4, 0,
  

In [41]:
centroids_pca = kmeans.cluster_centers_
centroids_pca

array([[ 0.18,  0.05, -0.27,  0.19,  0.03,  0.02],
       [-0.6 , -0.36,  0.11, -0.13, -0.13, -0.02],
       [ 1.41,  0.09,  0.04, -0.17, -0.03, -0.01],
       [-0.62,  0.64,  0.2 , -0.09, -0.07,  0.01],
       [-0.2 , -0.24,  0.15,  0.06,  0.13, -0.01],
       [ 0.44, -0.11,  0.17,  0.23, -0.05, -0.01],
       [-0.51, -0.06, -0.34, -0.07,  0.08,  0.01]])

In [42]:
print completeness_score(classes[1],clusters_pca)

0.6127090955256953


In [43]:
print homogeneity_score(classes[1],clusters_pca)

0.6110419970698139


In [ ]:
# 1.e discuss