In [84]:
import numpy as np
import pylab as pl
import pandas as pd
from sklearn.cluster import KMeans 
from sklearn import preprocessing

np.set_printoptions(precision=2, linewidth=500, suppress=True, threshold=np.nan)

#np.set_printoptions(threshold=np.nan)
#np.set_printoptions(linewidth=500)

from IPython.display import display
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [85]:
## 1.a load data

## Rows = images
## Columns = features

data = pd.read_csv('segmentation_data.txt', header=None)
classes = pd.read_table('segmentation_classes.txt', sep='\t', header=None)

In [86]:
data.head(10)

0      1   2         3    4         5         6         7         8   \
0  110.0  189.0   9  0.000000  0.0  1.000000  0.666667  1.222222  1.186342   
1   86.0  187.0   9  0.000000  0.0  1.111111  0.720082  1.444444  0.750309   
2  225.0  244.0   9  0.000000  0.0  3.388889  2.195113  3.000000  1.520234   
3   47.0  232.0   9  0.000000  0.0  1.277778  1.254621  1.000000  0.894427   
4   97.0  186.0   9  0.000000  0.0  1.166667  0.691215  1.166667  1.005540   
5  157.0  221.0   9  0.000000  0.0  1.055556  0.646930  1.222222  0.620633   
6   62.0  224.0   9  0.000000  0.0  0.944445  1.083547  2.333333  1.632993   
7   27.0  248.0   9  0.111111  0.0  1.611111  0.646930  3.166667  1.722401   
8   44.0  233.0   9  0.000000  0.0  2.222222  2.146487  2.111111  1.327766   
9   17.0  229.0   9  0.000000  0.0  2.111111  1.985130  2.444445  1.614747   

          9          10         11         12        13         14         15  \
0  12.925926  10.888889   9.222222  18.666668 -6.111111 -11.111111  17.222221   
1  13.740741  11.666667  10.333334  19.222221 -6.222222 -10.222222  16.444445   
2  12.259259  10.333334   9.333334  17.111110 -5.777778  -8.777778  14.555555   
3  12.703704  11.000000   9.000000  18.111110 -5.111111 -11.111111  16.222221   
4  15.592592  13.888889  11.777778  21.111110 -5.111111 -11.444445  16.555555   
5  12.111111  10.222222   8.111112  18.000000 -5.666666 -12.000000  17.666666   
6  14.629630  13.222222  11.444445  19.222221 -4.222222  -9.555555  13.777778   
7  15.296296  14.777778  12.888889  18.222221 -1.555556  -7.222222   8.777778   
8  14.481482  12.555555  11.333333  19.555555 -5.777778  -9.444445  15.222222   
9  13.703704  11.222222  11.111111  18.777779 -7.444445  -7.777778  15.222222   

          16        17        18  
0  18.666668  0.508139  1.910864  
1  19.222221  0.463329  1.941465  
2  17.111110  0.480149  1.987902  
3  18.111110  0.500966  1.875362  
4  21.111110  0.442661  1.863654  
5  18.000000  0.549180  1.877146  
6  19.222221  0.408965  1.860191  
7  18.222221  0.312227  1.783512  
8  19.555555  0.422174  1.950405  
9  18.777779  0.439852  2.099904

In [87]:
classes.head(10)

0  1
0  GRASS  0
1  GRASS  0
2  GRASS  0
3  GRASS  0
4  GRASS  0
5  GRASS  0
6  GRASS  0
7  GRASS  0
8  GRASS  0
9  GRASS  0

In [88]:
## 1.a Perform Min-Max Normalization

min_max_scaler = preprocessing.MinMaxScaler().fit(data)
data_norm = min_max_scaler.transform(data)


data_norm[0:5]

array([[0.43, 0.74, 0.  , 0.  , 0.  , 0.03, 0.  , 0.03, 0.  , 0.09, 0.08, 0.06, 0.13, 0.73, 0.01, 0.87, 0.12, 0.51, 0.83],
       [0.34, 0.73, 0.  , 0.  , 0.  , 0.04, 0.  , 0.03, 0.  , 0.1 , 0.09, 0.07, 0.13, 0.73, 0.02, 0.86, 0.13, 0.46, 0.84],
       [0.89, 0.97, 0.  , 0.  , 0.  , 0.12, 0.  , 0.07, 0.  , 0.09, 0.08, 0.06, 0.12, 0.74, 0.04, 0.83, 0.11, 0.48, 0.84],
       [0.18, 0.92, 0.  , 0.  , 0.  , 0.04, 0.  , 0.02, 0.  , 0.09, 0.08, 0.06, 0.13, 0.75, 0.01, 0.86, 0.12, 0.5 , 0.83],
       [0.38, 0.73, 0.  , 0.  , 0.  , 0.04, 0.  , 0.03, 0.  , 0.11, 0.1 , 0.08, 0.15, 0.75, 0.01, 0.86, 0.14, 0.44, 0.82]])

In [89]:
## 1.b perfrom Kmeans clustering

kmeans = KMeans(n_clusters=7, max_iter=500, verbose=1) # initialization
kmeans.fit(data_norm)

Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 417.57400876382485
start iteration
done sorting
end inner loop
Iteration 1, inertia 405.4676389875847
start iteration
done sorting
end inner loop
Iteration 2, inertia 397.72308840446806
start iteration
done sorting
end inner loop
Iteration 3, inertia 392.7340181821148
start iteration
done sorting
end inner loop
Iteration 4, inertia 390.5901518735033
start iteration
done sorting
end inner loop
Iteration 5, inertia 388.95764578903606
start iteration
done sorting
end inner loop
Iteration 6, inertia 386.5855495061893
start iteration
done sorting
end inner loop
Iteration 7, inertia 384.6165924573097
start iteration
done sorting
end inner loop
Iteration 8, inertia 382.16545027100415
start iteration
done sorting
end inner loop
Iteration 9, inertia 380.44388803506695
start iteration
done sorting
end inner loop
Iteration 10, inertia 378.7416107413326
start iteration
done sorting
end inner loop
Iteration 11,

start iteration
done sorting
end inner loop
Iteration 13, inertia 375.10652354921655
start iteration
done sorting
end inner loop
Iteration 14, inertia 374.8415129794841
start iteration
done sorting
end inner loop
Iteration 15, inertia 374.55871015167577
start iteration
done sorting
end inner loop
Iteration 16, inertia 374.4841858568177
start iteration
done sorting
end inner loop
Iteration 17, inertia 374.452922754192
start iteration
done sorting
end inner loop
Iteration 18, inertia 374.4319452102955
start iteration
done sorting
end inner loop
Iteration 19, inertia 374.42352420894053
start iteration
done sorting
end inner loop
Iteration 20, inertia 374.417947100683
start iteration
done sorting
end inner loop
Iteration 21, inertia 374.417947100683
center shift 0.000000e+00 within tolerance 4.150157e-06


KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=500,
    n_clusters=7, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=1)

In [90]:
clusters = kmeans.predict(data_norm)

In [91]:
clusters

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 4, 5, 5, 5, 5, 4, 4, 5, 5, 5, 5, 5, 5, 5, 4, 5, 5, 5, 5, 4, 5, 4, 5, 4, 5, 5, 5, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 5, 5, 5, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 5, 5, 5, 5, 4, 5, 4, 5, 5, 5, 4, 4, 4, 5, 4, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 4, 5, 5, 4, 5, 4, 4, 5, 6, 5, 4, 5, 4, 5, 4, 4, 4, 1, 4, 4, 5, 5, 4, 4, 4, 4, 5, 4, 5, 5, 4, 5, 5, 5, 4, 4, 4, 5, 1, 5, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 1, 4, 4, 4, 1, 4, 5, 4, 5, 5, 4, 4, 4, 5, 4, 1, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 4, 5, 5, 4, 5, 1, 4, 4, 5, 4, 4, 4, 5, 4, 1, 5,
  

In [92]:
centroids = kmeans.cluster_centers_

In [93]:
# 1.b print centroids

centroids

array([[0.51, 0.81, 0.  , 0.08, 0.01, 0.05, 0.  , 0.05, 0.  , 0.11, 0.09, 0.09, 0.14, 0.68, 0.08, 0.82, 0.13, 0.41, 0.89],
       [0.26, 0.39, 0.  , 0.07, 0.02, 0.08, 0.  , 0.06, 0.  , 0.15, 0.14, 0.19, 0.12, 0.72, 0.34, 0.36, 0.19, 0.41, 0.2 ],
       [0.54, 0.15, 0.  , 0.03, 0.  , 0.03, 0.  , 0.03, 0.  , 0.82, 0.78, 0.89, 0.79, 0.27, 0.67, 0.29, 0.89, 0.21, 0.13],
       [0.25, 0.46, 0.  , 0.03, 0.01, 0.04, 0.  , 0.03, 0.  , 0.03, 0.02, 0.04, 0.02, 0.77, 0.22, 0.51, 0.04, 0.8 , 0.18],
       [0.3 , 0.53, 0.  , 0.05, 0.05, 0.1 , 0.01, 0.08, 0.01, 0.4 , 0.37, 0.47, 0.35, 0.5 , 0.57, 0.21, 0.47, 0.3 , 0.16],
       [0.75, 0.53, 0.  , 0.04, 0.04, 0.11, 0.02, 0.11, 0.02, 0.3 , 0.28, 0.35, 0.27, 0.59, 0.45, 0.31, 0.35, 0.3 , 0.16],
       [0.77, 0.43, 0.  , 0.01, 0.02, 0.04, 0.  , 0.02, 0.  , 0.04, 0.03, 0.06, 0.03, 0.78, 0.22, 0.49, 0.06, 0.54, 0.24]])