In [2]:
import numpy as np
import pylab as pl
import pandas as pd
from sklearn.cluster import KMeans 
from sklearn import preprocessing

np.set_printoptions(precision=2, linewidth=500, suppress=True, threshold=np.nan)

from IPython.display import display
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [3]:
## 1.a load data

## Rows = images
## Columns = features

data = pd.read_csv('segmentation_data.txt', header=None)
classes = pd.read_table('segmentation_classes.txt', sep='\t', header=None)

In [4]:
data.head(10)

0      1   2         3    4         5         6         7         8   \
0  110.0  189.0   9  0.000000  0.0  1.000000  0.666667  1.222222  1.186342   
1   86.0  187.0   9  0.000000  0.0  1.111111  0.720082  1.444444  0.750309   
2  225.0  244.0   9  0.000000  0.0  3.388889  2.195113  3.000000  1.520234   
3   47.0  232.0   9  0.000000  0.0  1.277778  1.254621  1.000000  0.894427   
4   97.0  186.0   9  0.000000  0.0  1.166667  0.691215  1.166667  1.005540   
5  157.0  221.0   9  0.000000  0.0  1.055556  0.646930  1.222222  0.620633   
6   62.0  224.0   9  0.000000  0.0  0.944445  1.083547  2.333333  1.632993   
7   27.0  248.0   9  0.111111  0.0  1.611111  0.646930  3.166667  1.722401   
8   44.0  233.0   9  0.000000  0.0  2.222222  2.146487  2.111111  1.327766   
9   17.0  229.0   9  0.000000  0.0  2.111111  1.985130  2.444445  1.614747   

          9          10         11         12        13         14         15  \
0  12.925926  10.888889   9.222222  18.666668 -6.111111 -11.111111  17.222221   
1  13.740741  11.666667  10.333334  19.222221 -6.222222 -10.222222  16.444445   
2  12.259259  10.333334   9.333334  17.111110 -5.777778  -8.777778  14.555555   
3  12.703704  11.000000   9.000000  18.111110 -5.111111 -11.111111  16.222221   
4  15.592592  13.888889  11.777778  21.111110 -5.111111 -11.444445  16.555555   
5  12.111111  10.222222   8.111112  18.000000 -5.666666 -12.000000  17.666666   
6  14.629630  13.222222  11.444445  19.222221 -4.222222  -9.555555  13.777778   
7  15.296296  14.777778  12.888889  18.222221 -1.555556  -7.222222   8.777778   
8  14.481482  12.555555  11.333333  19.555555 -5.777778  -9.444445  15.222222   
9  13.703704  11.222222  11.111111  18.777779 -7.444445  -7.777778  15.222222   

          16        17        18  
0  18.666668  0.508139  1.910864  
1  19.222221  0.463329  1.941465  
2  17.111110  0.480149  1.987902  
3  18.111110  0.500966  1.875362  
4  21.111110  0.442661  1.863654  
5  18.000000  0.549180  1.877146  
6  19.222221  0.408965  1.860191  
7  18.222221  0.312227  1.783512  
8  19.555555  0.422174  1.950405  
9  18.777779  0.439852  2.099904

In [5]:
classes.head(10)

0  1
0  GRASS  0
1  GRASS  0
2  GRASS  0
3  GRASS  0
4  GRASS  0
5  GRASS  0
6  GRASS  0
7  GRASS  0
8  GRASS  0
9  GRASS  0

In [6]:
## 1.a Perform Min-Max Normalization

min_max_scaler = preprocessing.MinMaxScaler().fit(data)
data_norm = min_max_scaler.transform(data)


data_norm[0:5]

array([[0.43, 0.74, 0.  , 0.  , 0.  , 0.03, 0.  , 0.03, 0.  , 0.09, 0.08, 0.06, 0.13, 0.73, 0.01, 0.87, 0.12, 0.51, 0.83],
       [0.34, 0.73, 0.  , 0.  , 0.  , 0.04, 0.  , 0.03, 0.  , 0.1 , 0.09, 0.07, 0.13, 0.73, 0.02, 0.86, 0.13, 0.46, 0.84],
       [0.89, 0.97, 0.  , 0.  , 0.  , 0.12, 0.  , 0.07, 0.  , 0.09, 0.08, 0.06, 0.12, 0.74, 0.04, 0.83, 0.11, 0.48, 0.84],
       [0.18, 0.92, 0.  , 0.  , 0.  , 0.04, 0.  , 0.02, 0.  , 0.09, 0.08, 0.06, 0.13, 0.75, 0.01, 0.86, 0.12, 0.5 , 0.83],
       [0.38, 0.73, 0.  , 0.  , 0.  , 0.04, 0.  , 0.03, 0.  , 0.11, 0.1 , 0.08, 0.15, 0.75, 0.01, 0.86, 0.14, 0.44, 0.82]])

In [7]:
## 1.b perfrom Kmeans clustering

kmeans = KMeans(n_clusters=7, max_iter=500, verbose=1) # initialization
kmeans.fit(data_norm)

Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 393.55253600317485
start iteration
done sorting
end inner loop
Iteration 1, inertia 377.3415664299792
start iteration
done sorting
end inner loop
Iteration 2, inertia 371.95022702345227
start iteration
done sorting
end inner loop
Iteration 3, inertia 368.7614911878723
start iteration
done sorting
end inner loop
Iteration 4, inertia 365.8943173127615
start iteration
done sorting
end inner loop
Iteration 5, inertia 360.978400207175
start iteration
done sorting
end inner loop
Iteration 6, inertia 356.93195446961056
start iteration
done sorting
end inner loop
Iteration 7, inertia 354.6746605428959
start iteration
done sorting
end inner loop
Iteration 8, inertia 352.9810883094277
start iteration
done sorting
end inner loop
Iteration 9, inertia 351.6624011410965
start iteration
done sorting
end inner loop
Iteration 10, inertia 351.3672713115442
start iteration
done sorting
end inner loop
Iteration 11, in

Iteration 23, inertia 373.33120998440637
start iteration
done sorting
end inner loop
Iteration 24, inertia 373.328089525486
center shift 1.764227e-03 within tolerance 4.150157e-06
Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 407.2251625134186
start iteration
done sorting
end inner loop
Iteration 1, inertia 387.20485681363255
start iteration
done sorting
end inner loop
Iteration 2, inertia 380.4559119543328
start iteration
done sorting
end inner loop
Iteration 3, inertia 377.7843306014475
start iteration
done sorting
end inner loop
Iteration 4, inertia 376.3190529460212
start iteration
done sorting
end inner loop
Iteration 5, inertia 375.5626983691851
start iteration
done sorting
end inner loop
Iteration 6, inertia 374.88843780423036
start iteration
done sorting
end inner loop
Iteration 7, inertia 374.21464450047637
start iteration
done sorting
end inner loop
Iteration 8, inertia 373.89900755116605
start iteration
done sorting
end inner loop
I

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=500,
    n_clusters=7, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=1)

In [8]:
clusters = kmeans.predict(data_norm)

In [9]:
clusters

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 6, 4, 4, 4, 4, 6, 6, 4, 4, 4, 4, 4, 4, 4, 6, 4, 4, 4, 4, 6, 4, 6, 4, 6, 4, 4, 4, 4, 4, 6, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 4, 6, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 4, 4, 4, 4, 4, 6, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 4, 4, 4, 4, 6, 4, 6, 4, 4, 4, 6, 6, 6, 4, 6, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 5, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 6, 4, 4, 6, 4, 6, 6, 4, 3, 4, 6, 4, 6, 4, 6, 6, 6, 0, 6, 6, 4, 4, 6, 6, 6, 6, 4, 6, 4, 4, 6, 4, 4, 4, 6, 6, 6, 4, 0, 4, 6, 6, 6, 6, 6, 4, 4, 4, 4, 4, 0, 6, 6, 6, 0, 6, 4, 6, 4, 4, 6, 6, 6, 4, 6, 0, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 4, 4, 4, 6, 4, 4, 6, 4, 0, 6, 6, 4, 6, 6, 6, 4, 6, 0, 4,
  

In [10]:
centroids = kmeans.cluster_centers_

In [11]:
# 1.b print centroids

centroids

array([[0.25, 0.39, 0.  , 0.08, 0.02, 0.08, 0.  , 0.06, 0.01, 0.15, 0.14, 0.18, 0.12, 0.72, 0.34, 0.35, 0.18, 0.41, 0.2 ],
       [0.54, 0.15, 0.  , 0.03, 0.  , 0.03, 0.  , 0.03, 0.  , 0.82, 0.78, 0.89, 0.79, 0.27, 0.67, 0.29, 0.89, 0.21, 0.13],
       [0.51, 0.81, 0.  , 0.08, 0.01, 0.05, 0.  , 0.05, 0.  , 0.11, 0.09, 0.09, 0.14, 0.68, 0.08, 0.82, 0.13, 0.41, 0.89],
       [0.77, 0.43, 0.  , 0.01, 0.02, 0.04, 0.  , 0.02, 0.  , 0.04, 0.03, 0.06, 0.03, 0.78, 0.22, 0.49, 0.06, 0.54, 0.24],
       [0.75, 0.53, 0.  , 0.04, 0.04, 0.11, 0.02, 0.11, 0.02, 0.3 , 0.28, 0.35, 0.26, 0.59, 0.45, 0.31, 0.35, 0.3 , 0.16],
       [0.25, 0.46, 0.  , 0.03, 0.01, 0.04, 0.  , 0.03, 0.  , 0.03, 0.02, 0.04, 0.02, 0.77, 0.22, 0.51, 0.04, 0.8 , 0.18],
       [0.3 , 0.53, 0.  , 0.05, 0.05, 0.1 , 0.01, 0.08, 0.01, 0.4 , 0.37, 0.47, 0.35, 0.5 , 0.57, 0.21, 0.47, 0.3 , 0.16]])

In [12]:
# 1.b completeness and homogeneity

from sklearn.metrics import completeness_score, homogeneity_score

In [13]:
print completeness_score(classes[1],clusters)

0.6117374684331666


In [14]:
print homogeneity_score(classes[1],clusters)

0.6100499914689615


In [15]:
# 1.c Perform PCA

from sklearn import decomposition
pca = decomposition.PCA(n_components=6)

data_trans = pca.fit(data_norm).transform(data_norm)
print data_trans

[[-0.69  0.53  0.25 -0.2  -0.08  0.05]
 [-0.67  0.51  0.34 -0.17 -0.04  0.06]
 [-0.71  0.77 -0.16 -0.01 -0.17  0.04]
 [-0.73  0.51  0.5  -0.06 -0.14  0.03]
 [-0.64  0.53  0.3  -0.18 -0.02  0.05]
 [-0.73  0.63  0.08 -0.14 -0.17  0.02]
 [-0.67  0.53  0.44 -0.02 -0.06  0.03]
 [-0.66  0.52  0.59  0.15  0.01 -0.17]
 [-0.69  0.53  0.52 -0.01 -0.1   0.05]
 [-0.69  0.5   0.62 -0.02 -0.12  0.06]
 [-0.73  0.52  0.56 -0.01 -0.15  0.04]
 [-0.68  0.51  0.47 -0.04 -0.02 -0.15]
 [-0.72  0.59  0.15 -0.16 -0.14  0.05]
 [-0.69  0.52  0.32 -0.19 -0.08  0.05]
 [-0.77  0.77 -0.23 -0.07 -0.23 -0.19]
 [-0.72  0.5   0.45 -0.08 -0.12  0.04]
 [-0.74  0.57  0.11 -0.19 -0.14  0.02]
 [-0.66  0.42  0.58 -0.15 -0.    0.05]
 [-0.53  0.79 -0.23 -0.18  0.02  0.05]
 [-0.61  0.74 -0.16 -0.22 -0.01 -0.15]
 [-0.71  0.52  0.37 -0.15 -0.12  0.06]
 [-0.68  0.66 -0.02 -0.16 -0.13  0.09]
 [-0.67  0.59  0.38 -0.04 -0.07 -0.15]
 [-0.7   0.71  0.1  -0.03 -0.14 -0.15]
 [-0.64  0.69  0.27  0.03 -0.12  0.05]
 [-0.62  0.48  0.5  -0.1 

In [16]:
# six components explain 95% of the variance

print(pca.explained_variance_ratio_)

[0.61 0.13 0.1  0.05 0.04 0.02]


In [17]:
# 1.c Perform kmeans on reduced dimensions

kmeans = KMeans(n_clusters=7, max_iter=500, verbose=1) # initialization
kmeans.fit(data_trans)

Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 265.92304256722747
start iteration
done sorting
end inner loop
Iteration 1, inertia 258.6856238135665
start iteration
done sorting
end inner loop
Iteration 2, inertia 257.84432131471056
start iteration
done sorting
end inner loop
Iteration 3, inertia 257.6796989819912
start iteration
done sorting
end inner loop
Iteration 4, inertia 257.6406717583459
start iteration
done sorting
end inner loop
Iteration 5, inertia 257.62685157492837
start iteration
done sorting
end inner loop
Iteration 6, inertia 257.59904685230117
start iteration
done sorting
end inner loop
Iteration 7, inertia 257.5502835221131
start iteration
done sorting
end inner loop
Iteration 8, inertia 257.45054516709376
start iteration
done sorting
end inner loop
Iteration 9, inertia 257.29601977464154
start iteration
done sorting
end inner loop
Iteration 10, inertia 257.0581583214147
start iteration
done sorting
end inner loop
Iteration 11

Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 326.6094060232938
start iteration
done sorting
end inner loop
Iteration 1, inertia 314.98757176747677
start iteration
done sorting
end inner loop
Iteration 2, inertia 310.3592705085661
start iteration
done sorting
end inner loop
Iteration 3, inertia 305.4935852644835
start iteration
done sorting
end inner loop
Iteration 4, inertia 301.60516107347013
start iteration
done sorting
end inner loop
Iteration 5, inertia 300.4111465266352
start iteration
done sorting
end inner loop
Iteration 6, inertia 299.17823970271075
start iteration
done sorting
end inner loop
Iteration 7, inertia 298.5204209591057
start iteration
done sorting
end inner loop
Iteration 8, inertia 298.10801493995325
start iteration
done sorting
end inner loop
Iteration 9, inertia 297.8742045007452
start iteration
done sorting
end inner loop
Iteration 10, inertia 297.75299684854485
start iteration
done sorting
end inner loop
Iteration 11,

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=500,
    n_clusters=7, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=1)

In [18]:
clusters_pca = kmeans.predict(data_trans)
clusters_pca

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 6, 4, 6, 6, 6, 6, 4, 4, 6, 6, 6, 6, 6, 6, 6, 4, 6, 6, 6, 6, 4, 6, 4, 6, 4, 6, 6, 6, 6, 6, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 4, 6, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 4, 6, 6, 6, 6, 6, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 4, 6, 6, 6, 6, 4, 6, 4, 6, 6, 6, 4, 4, 4, 6, 4, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 6, 6, 4, 6, 4, 4, 6, 5, 6, 4, 6, 4, 6, 4, 4, 4, 0, 4, 4, 6, 6, 4, 4, 4, 4, 6, 4, 6, 6, 4, 6, 6, 6, 4, 4, 4, 6, 0, 6, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6, 0, 4, 4, 4, 0, 4, 6, 4, 6, 6, 4, 4, 4, 6, 4, 0, 6, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 4, 6, 6, 4, 6, 0, 4, 4, 6, 4, 4, 4, 6, 4, 0, 6,
  

In [19]:
centroids_pca = kmeans.cluster_centers_
centroids_pca

array([[-0.2 , -0.24,  0.15,  0.06,  0.13, -0.01],
       [ 1.41,  0.09,  0.04, -0.17, -0.03, -0.01],
       [-0.62,  0.64,  0.2 , -0.09, -0.06,  0.01],
       [-0.6 , -0.36,  0.11, -0.13, -0.13, -0.02],
       [ 0.44, -0.11,  0.17,  0.24, -0.05, -0.01],
       [-0.51, -0.07, -0.34, -0.07,  0.07,  0.01],
       [ 0.18,  0.05, -0.27,  0.19,  0.03,  0.02]])

In [20]:
print completeness_score(classes[1],clusters_pca)

0.6096968341816197


In [21]:
print homogeneity_score(classes[1],clusters_pca)

0.6080039254811925


In [22]:
# 1.e discuss

# something like expected to see slightly lower scores, but yet very close with fewer features.

In [23]:
# 2

jokes = pd.read_csv('jokes.csv', header=None)
ratings = pd.read_csv('modified_jester_data.csv', header=None)

In [24]:
jokes.head(10)

0                                                  1
0  0  A man visits the doctor. The doctor says "I ha...
1  1  This couple had an excellent relationship goin...
2  2  Q. What's 200 feet long and has 4 teeth? A. Th...
3  3  Q. What's the difference between a man and a t...
4  4  Q. What's O. J. Simpson's Internet address? A....
5  5  Bill & Hillary are on a trip back to Arkansas....
6  6  How many feminists does it take to screw in a ...
7  7  Q. Did you hear about the dyslexic devil worsh...
8  8  A country guy goes into a city bar that has a ...
9  9  Two cannibals are eating a clown one turns to ...

In [25]:
ratings.head(10)

0      1      2      3      4      5      6      7      8      9   \
0   3.18  19.79   1.34   2.84   3.48   2.50   1.15  15.17   2.02   6.24   
1  15.08  10.71  17.36  15.37   8.62   1.34  10.27   5.66  19.88  20.22   
2   0.00   0.00   0.00   0.00  20.03  20.27  20.03  20.27   0.00   0.00   
3   0.00  19.35   0.00   0.00  12.80  19.16   8.18  17.21   0.00  12.84   
4  19.50  15.61   6.83   5.61  12.36  12.60  18.04  15.61  10.56  16.73   
5   4.83   7.46  11.44   2.50   3.91   6.68   2.31  10.13   4.35   9.20   
6   0.00   0.00   0.00   0.00  19.59   1.15  18.72  19.79   0.00   0.00   
7  17.84  14.16  20.17   4.79   2.84   9.30  20.27  12.41   5.81   6.58   
8   7.21   7.46   1.58   4.11   2.26  10.71   5.71   2.07   3.14   9.40   
9  14.01  16.15  16.15  14.01  17.41  16.15  19.93  13.52  14.01  19.16   

      10     11     12     13     14     15     16     17     18     19  \
0   2.50   4.25   3.82  19.45   3.82   3.48   3.57   1.19   1.15   1.15   
1  17.75  19.64  15.42  18.43  15.56  10.03  15.66  10.32  14.30   9.79   
2  18.33  18.57  20.37  17.17   4.64   4.11   3.14  20.03  20.03  20.03   
3  18.33  17.60  17.31  19.11   3.77   4.35  12.17   4.40   7.36   8.91   
4  19.25  17.84   7.07  18.23   8.67   1.34  13.72   9.64  13.57  15.51   
5   4.20   5.27   6.00   2.41  11.49   2.07   7.31   8.82   8.72   4.88   
6  15.27  18.62   4.74  13.96  17.07   7.50   8.91  17.17  16.15  15.42   
7  19.20   3.14   4.06   3.04  11.29   1.10   3.91   3.82  12.02  10.71   
8   8.09  10.71   6.15  10.51   2.26   4.01   2.26   8.09   7.65  10.71   
9  16.53  17.02  15.47  16.44   6.34  10.03  10.56  12.55  11.49  15.37   

      20     21     22     23     24     25     26     27     28     29  \
0   1.63  12.50   6.63   1.19   2.50  12.12  18.82  13.86  20.13   3.57   
1  11.87  19.64  19.35  20.17  11.05  18.57  15.71  11.87  10.61  17.99   
2  18.28   0.00  19.25   0.00   0.00  18.48  18.28  18.28  19.93   0.00   
3  16.34   0.00   0.00   0.00   0.00  13.91  14.93  17.75  17.60   0.00   
4  19.20  17.12  19.30   9.74  18.77  12.89   9.83  16.68  19.45  15.61   
5   7.99  10.42   8.62   3.23   8.77   8.72   5.76   5.47  10.32   4.06   
6  16.63  13.43   0.00   0.00  15.13  18.09  18.33  18.18  11.92   0.00   
7   6.29   3.57  12.12   2.75  14.79  11.10  14.45   7.55  18.57   6.83   
8  14.98   9.40  10.71  12.21  14.79  13.91  15.85  13.28  11.97  10.71   
9  16.44  16.24  17.60  14.01  17.02  17.80  13.91  16.15  14.50  16.15   

      30     31     32     33     34     35     36     37     38     39  \
0  13.14   6.92   1.92  18.82  16.05  15.95   1.83   2.60   2.60   2.60   
1  17.50  10.08  18.14  20.03   9.20  11.73  18.09  14.40  10.13  18.91   
2  17.17  18.28   0.00   0.00  19.98  18.33   0.00  17.17  20.08  18.33   
3  17.65   4.88   0.00  18.57  17.21  17.65   0.00   2.70  18.18  13.82   
4  19.06   1.53  18.28  16.68  13.48  14.20   9.74  17.80  15.51  13.48   
5   7.07  10.66   4.40   5.51   9.45  10.51   4.79   2.94   5.61   3.96   
6  16.15  16.87   0.00   0.00  18.96  14.79   0.00  12.55   0.00  14.11   
7  10.56  20.27  16.83   7.60   5.56  12.60   3.86  14.01   4.93  16.68   
8  17.36  11.53  10.71  15.66  14.35  11.97   7.89   9.16  15.42   6.58   
9  17.60  10.90  14.11  17.50  20.22  18.86  14.01  17.50  14.01  18.67   

      40     41     42     43     44     45     46     47     48     49  \
0   2.89   1.87   1.97   1.92   3.86   4.74  14.79  10.90  14.93  15.13   
1  18.82   7.17  19.64  19.98   6.68   7.80   6.10  10.08   9.54  14.64   
2  18.52  20.27  20.27   0.00  20.27   0.00  17.17  18.33  20.08  18.28   
3   0.00  12.55   0.00   0.00   0.00  17.84  17.84   7.02  17.99  14.45   
4  11.34  17.84  11.19   2.26  16.24  17.31  19.06  12.26  15.51  10.95   
5   2.17   3.09  12.07   9.11   4.64   6.78   1.73   1.19   3.18  10.37   
6  17.26   0.00   0.00   0.00  17.99  14.20   0.00  18.33  15.71  14.54   
7   4.54   6.58   2.02  11.53   9.74   6.58   2.07  19.93  10.90  18.43   
8   9.59  12.41   5.66   4.